version: '3.2'

services:
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - api

  frontend-dev:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - ./frontend/vue:/app
    command: npm run dev
    user: node
    ports:
      - ${FRONTEND_PORT}:5173
    depends_on:
      - api

  api:
    env_file:
      - .env
    build: api
    ports:
      - ${BACKEND_PORT}:80
    # todo: remove all volumes, make the image self-contained
    volumes:
      - composer-cache:/root/.composer/cache:rw
      - ./:/app
    networks:
      - backend-network
    depends_on:
      - mysql

  console:
    env_file:
      - .env
    build: console
    command: tail -F anything
    # todo: remove all volumes, make the image self-contained
    volumes:
      - composer-cache:/root/.composer/cache:rw
      - ./:/app
    depends_on:
      - mysql
    networks:
      - backend-network

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    ports:
    # for external/host database management
      - ${DB_PORT}:3306
    networks:
      - backend-network

volumes:
  composer-cache:

networks:
  backend-network: