version: '3.2'

services:
  vendor-shared:
    image: vendor-shared
    build:
      context: .
      dockerfile: ./infra/composer/Dockerfile
    command: exit

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./infra/api/Dockerfile
    ports:
      - ${BACKEND_PORT}:80
    networks:
      - backend-network
    depends_on:
      - mysql
      - vendor-shared

  console:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./infra/console/Dockerfile
    command: tail -F anything
    depends_on:
      - mysql
      - vendor-shared
    networks:
      - backend-network

  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./infra/frontend/Dockerfile
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - api

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    networks:
      - backend-network

networks:
  backend-network: